"""create initial ps83 schema

Revision ID: 333567f19fc8
Revises: 
Create Date: 2026-08-29 14:31:24.927955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '333567f19fc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geographic_zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('zone_name', sa.String(length=150), nullable=False),
    sa.Column('zone_type', sa.String(length=30), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_geographic_zones_zone_code'), 'geographic_zones', ['zone_code'], unique=True)
    op.create_table('intervention_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_rules_risk_level'), 'intervention_rules', ['risk_level'], unique=False)
    op.create_table('weather_stations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_code', sa.String(length=100), nullable=False),
    sa.Column('station_name', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_weather_stations_station_code'), 'weather_stations', ['station_code'], unique=True)
    op.create_table('demographic_vulnerability',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('elderly_population', sa.Integer(), nullable=True),
    sa.Column('children_population', sa.Integer(), nullable=True),
    sa.Column('outdoor_worker_population', sa.Integer(), nullable=True),
    sa.Column('population_density_per_km2', sa.Float(), nullable=True),
    sa.Column('vulnerability_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['geographic_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'reference_year', name='uq_demographic_zone_year')
    )
    op.create_index(op.f('ix_demographic_vulnerability_zone_id'), 'demographic_vulnerability', ['zone_id'], unique=False)
    op.create_table('health_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('geographic_resolution', sa.String(length=30), nullable=False),
    sa.Column('total_deaths', sa.Integer(), nullable=True),
    sa.Column('heat_related_deaths', sa.Integer(), nullable=True),
    sa.Column('total_hospitalizations', sa.Integer(), nullable=True),
    sa.Column('heat_related_hospitalizations', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['geographic_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_outcomes_observation_date'), 'health_outcomes', ['observation_date'], unique=False)
    op.create_index(op.f('ix_health_outcomes_zone_id'), 'health_outcomes', ['zone_id'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thermal_risk_score', sa.Float(), nullable=True),
    sa.Column('mortality_risk_score', sa.Float(), nullable=True),
    sa.Column('hospitalization_risk_score', sa.Float(), nullable=True),
    sa.Column('overall_risk_level', sa.String(length=30), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['geographic_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'prediction_generated_at', 'prediction_for', 'model_version', name='uq_risk_prediction_zone_generation_target_model')
    )
    op.create_index(op.f('ix_risk_predictions_prediction_for'), 'risk_predictions', ['prediction_for'], unique=False)
    op.create_index(op.f('ix_risk_predictions_zone_id'), 'risk_predictions', ['zone_id'], unique=False)
    op.create_table('thermal_indices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utci_c', sa.Float(), nullable=True),
    sa.Column('wbgt_c', sa.Float(), nullable=True),
    sa.Column('heat_index_c', sa.Float(), nullable=True),
    sa.Column('thermal_risk_level', sa.String(length=30), nullable=True),
    sa.Column('calculation_type', sa.String(length=20), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['weather_stations.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['geographic_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thermal_indices_station_id'), 'thermal_indices', ['station_id'], unique=False)
    op.create_index(op.f('ix_thermal_indices_valid_for'), 'thermal_indices', ['valid_for'], unique=False)
    op.create_index(op.f('ix_thermal_indices_zone_id'), 'thermal_indices', ['zone_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('air_temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('solar_radiation_wm2', sa.Float(), nullable=True),
    sa.Column('atmospheric_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['weather_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'forecast_generated_at', 'forecast_for', name='uq_weather_forecast_station_generation_target')
    )
    op.create_index(op.f('ix_weather_forecasts_forecast_for'), 'weather_forecasts', ['forecast_for'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_station_id'), 'weather_forecasts', ['station_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('air_temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('solar_radiation_wm2', sa.Float(), nullable=True),
    sa.Column('atmospheric_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['weather_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'observed_at', name='uq_weather_observation_station_time')
    )
    op.create_index(op.f('ix_weather_observations_observed_at'), 'weather_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_station_id'), 'weather_observations', ['station_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('risk_prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_level', sa.String(length=30), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['risk_prediction_id'], ['risk_predictions.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['geographic_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_risk_prediction_id'), 'alerts', ['risk_prediction_id'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_prediction_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_weather_observations_station_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_observed_at'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_weather_forecasts_station_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_for'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_thermal_indices_zone_id'), table_name='thermal_indices')
    op.drop_index(op.f('ix_thermal_indices_valid_for'), table_name='thermal_indices')
    op.drop_index(op.f('ix_thermal_indices_station_id'), table_name='thermal_indices')
    op.drop_table('thermal_indices')
    op.drop_index(op.f('ix_risk_predictions_zone_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_prediction_for'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_health_outcomes_zone_id'), table_name='health_outcomes')
    op.drop_index(op.f('ix_health_outcomes_observation_date'), table_name='health_outcomes')
    op.drop_table('health_outcomes')
    op.drop_index(op.f('ix_demographic_vulnerability_zone_id'), table_name='demographic_vulnerability')
    op.drop_table('demographic_vulnerability')
    op.drop_index(op.f('ix_weather_stations_station_code'), table_name='weather_stations')
    op.drop_table('weather_stations')
    op.drop_index(op.f('ix_intervention_rules_risk_level'), table_name='intervention_rules')
    op.drop_table('intervention_rules')
    op.drop_index(op.f('ix_geographic_zones_zone_code'), table_name='geographic_zones')
    
    op.drop_table('geographic_zones')
    # ### end Alembic commands ###
