"""add solar radiation components

Revision ID: 90e07dff9b52
Revises: 333567f19fc8
Create Date: 2026-08-29 15:56:07.521246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e07dff9b52'
down_revision: Union[str, Sequence[str], None] = '333567f19fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecasts', sa.Column('direct_radiation_wm2', sa.Float(), nullable=True))
    op.add_column('weather_forecasts', sa.Column('diffuse_radiation_wm2', sa.Float(), nullable=True))
    op.add_column('weather_forecasts', sa.Column('direct_normal_irradiance_wm2', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('direct_radiation_wm2', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('diffuse_radiation_wm2', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('direct_normal_irradiance_wm2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_observations', 'direct_normal_irradiance_wm2')
    op.drop_column('weather_observations', 'diffuse_radiation_wm2')
    op.drop_column('weather_observations', 'direct_radiation_wm2')
    op.drop_column('weather_forecasts', 'direct_normal_irradiance_wm2')
    op.drop_column('weather_forecasts', 'diffuse_radiation_wm2')
    op.drop_column('weather_forecasts', 'direct_radiation_wm2')
    # ### end Alembic commands ###
